export const COMMAND_DISPATCHER_KEY = Symbol('COMMAND_DISPATCHER_KEY');
export const QUERY_DISPATCHER_KEY = Symbol('QUERY_DISPATCHER_KEY');
export const EVENTS_DISPATHCER_KEY = Symbol('EVENTS_DISPATHCER_KEY');
export const EXPLORER_SERVICE_KEY = Symbol('EXPLORER_SERVICE_KEY');
