version: '3.8'

name: teachflow

services:
  postgres:
    image: postgres:17.5
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-myuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mypassword}
      - POSTGRES_DB=${POSTGRES_DB:-mydatabase}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - '${POSTGRES_DATA_DIR:-./.postgres_data}:/var/lib/postgresql/data'
    networks:
      - platform
    restart: unless-stopped

  app:
    build: .
    container_name: application
    ports:
      - '${APP_HOST_PORT:-3000}:${APP_SERVICE_PORT_INTERNAL:-3000}'
    depends_on:
      - postgres
    environment:
      - APP_PORT=${APP_SERVICE_PORT_INTERNAL:-3000}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-myuser}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-mypassword}
      - DB_NAME=${POSTGRES_DB:-mydatabase}
    networks:
      - platform

networks:
  platform:
    driver: bridge
